language: rust
sudo: required
dist: bionic

INSTALL_NODE_VIA_NVM: &INSTALL_NODE_VIA_NVM
  |
    rustup target add wasm32-unknown-unknown
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    source ~/.nvm/nvm.sh
    nvm install lts/carbon


cache: cargo

addons:
  apt:
    packages:
    - wine-stable
    # - xvfb

matrix:
  include:

  - name: BuildWeb
    env: RUST_BACKTRACE=1
    rust: stable
    install:
      - *INSTALL_NODE_VIA_NVM
      - npm install -g cordova
      - cargo install wasm-pack
      - npm install
    script:
    - npm run build
    - bash build_and_fixcordova.sh