language: rust
sudo: required
dist: bionic

INSTALL_NODE_VIA_NVM: &INSTALL_NODE_VIA_NVM
  |
    rustup target add wasm32-unknown-unknown
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    source ~/.nvm/nvm.sh
    nvm install lts/carbon


cache: cargo

addons:
  apt:
    packages:
    - wine-stable
    - wine32
    # - xvfb

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Deep"
  - git config --local user.email "deepgauravraj@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: deploys/*
  skip_cleanup: true

matrix:
  include:

  - name: BuildWeb
    env: RUST_BACKTRACE=1
    rust: stable
    install:
      - *INSTALL_NODE_VIA_NVM
      - npm install -g cordova
      - npm install
    script:
      - curl -L https://github.com/rustwasm/wasm-pack/releases/download/v0.9.1/wasm-pack-v0.9.1-x86_64-unknown-linux-musl.tar.gz --output wasm-pack.tar.gz
      - tar -zxvf wasm-pack.tar.gz
      - export PATH="$PATH:$PWD/wasm-pack"
      - export WASM_PACK_PATH="$PWD/wasm-pack/wasm-pack"
      - npm run build
      - bash build_and_fixcordova.sh